name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, json
          coverage: none
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
      - name: Lint (PHPCS)
        run: |
          vendor/bin/phpcs -q --standard=phpcs.xml.dist --extensions=php,inc || true
      - name: Static analysis (PHPStan)
        run: |
          vendor/bin/phpstan analyse -c phpstan.neon.dist --no-progress
      - name: Tests (PHPUnit)
        run: |
          vendor/bin/phpunit -c phpunit.xml.dist


